name: deploy

on:
  push:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: build Dockerfile
            run: docker buildx build -t ${{secrets.DOCKER_USERNAME}}/machine-learning .

          - name: Login docker hub
            uses: docker/login-action@v1
            with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}

          - name: Push Docker Image
            run: docker push ${{secrets.DOCKER_USERNAME}}/machine-learning

          - name: run scrpt
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                  docker run -d ${{secrets.DOCKER_USERNAME}}/machine-learning
                  
